java_library(
    name = "util",
    srcs = glob(["*.java"]),
    deps = ["//dependencies/maven/artifacts/com/google/protobuf:protobuf-java"],
    visibility = ["//visibility:public"],
    tags = ["maven_coordinates=io.grabl.tracing:grabl-tracing-util:{pom_version}"],
)